### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'split'

### ISSUE THREAD

**Issue by chrisamiller** [griffithlab/VAtools#47]
I've got a minimal VCF attached that reliably crashes vep-annotation-reporter. A half dozen VCF are failing with the same error, another dozen or so run just fine.  

This command will reliably crash it from the most recent docker version: `griffithlab/vatools:4.1.0` 

    vep-annotation-reporter -t zz.tsv -o zz.anno.tsv zz.vep.vcf Consequence

First variant line alone works fine, add the second line, and it crashes with the following error:

```Traceback (most recent call last):
  File "/usr/local/bin/vep-annotation-reporter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/vatools/vep_annotation_reporter.py", line 167, in main
    vep = extract_vep_fields(args)
  File "/usr/local/lib/python3.6/dist-packages/vatools/vep_annotation_reporter.py", line 114, in extract_vep_fields
    for variant in vcf_reader:
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/reader.py", line 175, in __next__
    result = self.parser.parse_next_record()
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/parser.py", line 802, in parse_next_record
    return self.parse_line(self._read_next_line())
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/parser.py", line 793, in parse_line
    return self._record_parser.parse_line(line)
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/parser.py", line 457, in parse_line
    info = self._parse_info(arr[7], len(alts))
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/parser.py", line 535, in _parse_info
    result[key] = parse_field_value(self.header.get_info_field_info(key), True)
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/parser.py", line 271, in parse_field_value
    return [convert_field_value(field_info.type, x) for x in value.split(",")]
AttributeError: 'bool' object has no attribute 'split'
```
I've done some basic sanity checking on the VCF fields to try to figure out what the issue is, but haven't been able to nail it down. I think debugging from within the python tool is going to be necessary, unless I've missed something obvious!

[vcf.tar.gz](https://github.com/griffithlab/VAtools/files/5892117/vcf.tar.gz)

**Comment by susannasiebert** [comment]
This error is caused by a malformed header line for a boolean field. The `hotspot` INFO field is described like this:
```
<ID=hotspot,Number=A,Type=Float,Description="Known somatic site, used to increase confidence in call">
```
but the actual INFO entry is a Flag. 

Updating the header to
```
<ID=hotspot,Number=0,Type=Flag,Description="Known somatic site, used to increase confidence in call">
```
should fix this issue.

**Comment by chrisamiller** [comment]
Yep, fixing that header line with a quick regex like this fixed the issue - thanks!

`sed 's/ID=hotspot,Number=A,Type=Float/ID=hotspot,Number=0,Type=Flag/g'`
