### ISSUE TITLE
vep_annotation_reporter.py + AttributeError: 'bool' object has no attribute 'split'

### ISSUE THREAD

**Issue by arumds** [griffithlab/VAtools#48]
Hi,

We have tried using VAtools tools installed with the command ```sudo pip3 install vatools``` to get a tsv file and stuck with the below python specific error.  The input is a Annovar+VEP annotated VCF. 

1) Could you help to fix the below error.
2) How do we get the binary installation to run as ```vep-annotation-reporter``` instead of ```vep_annotation_reporter.py```

```
$ python3 /vatools/vep_annotation_reporter.py -o hg38_multianno.vep.tsv hg38_multianno.vep.vcf.gz Allele Consequence IMPACT SYMBOL Gene Feature_type Feature BIOTYPE EXON INTRON HGVSc HGVSp cDNA_position CDS_position Protein_position Amino_acids Codons Existing_variation DISTANCE STRAND FLAGS VARIANT_CLASS SYMBOL_SOURCE HGNC_ID CANONICAL MANE TSL CCDS ENSP SpliceAI_pred_DP_AG SpliceAI_pred_DP_AL SpliceAI_pred_DP_DG SpliceAI_pred_DP_DL SpliceAI_pred_DS_AG SpliceAI_pred_DS_AL SpliceAI_pred_DS_DG SpliceAI_pred_DS_DL SpliceAI_pred_SYMBOL
/usr/local/lib/python3.8/dist-packages/vcfpy/header.py:413: FieldInfoNotFound: INFO . not found using String/'.' instead
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/vatools/vep_annotation_reporter.py", line 202, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/vatools/vep_annotation_reporter.py", line 167, in main
    vep = extract_vep_fields(args)
  File "/usr/local/lib/python3.8/dist-packages/vatools/vep_annotation_reporter.py", line 114, in extract_vep_fields
    for variant in vcf_reader:
  File "/usr/local/lib/python3.8/dist-packages/vcfpy/reader.py", line 175, in __next__
    result = self.parser.parse_next_record()
  File "/usr/local/lib/python3.8/dist-packages/vcfpy/parser.py", line 802, in parse_next_record
    return self.parse_line(self._read_next_line())
  File "/usr/local/lib/python3.8/dist-packages/vcfpy/parser.py", line 793, in parse_line
    return self._record_parser.parse_line(line)
  File "/usr/local/lib/python3.8/dist-packages/vcfpy/parser.py", line 457, in parse_line
    info = self._parse_info(arr[7], len(alts))
  File "/usr/local/lib/python3.8/dist-packages/vcfpy/parser.py", line 535, in _parse_info
    result[key] = parse_field_value(self.header.get_info_field_info(key), True)
  File "/usr/local/lib/python3.8/dist-packages/vcfpy/parser.py", line 271, in parse_field_value
    return [convert_field_value(field_info.type, x) for x in value.split(",")]
AttributeError: 'bool' object has no attribute 'split'
```

**Comment by susannasiebert** [comment]
Would you be able to share your VCF with us? This error usually indicates a mismatch between the header definition and the contents of one of the VCF fields (i.e., some data is not in the format that is specified by its header line). I would need to debug your VCF to figure out which field specifically is the problem.

In regards to your installation question: `sudo pip3 install vatools` did not work for you? Can you please give me some more information on the installation steps you took?

**Comment by arumds** [comment]
The issue is with the VCF file. It has some missing fields in some rows. It works now after fixing the VCF.

**Comment by susannasiebert** [comment]
Glad to hear that. I'll close this issue.
